In [6]:
# import numpy as np

## 모듈사용하기

In [129]:
import numpy 

In [ ]:
from random import rand, randint

In [2]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [5]:
type(arr1)

numpy.ndarray

In [7]:
list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [9]:
arr1 = np.array(list1)  # 리스트를 넘파이 배열로 생성


In [11]:
arr1
type(arr1)

numpy.ndarray

In [12]:
arr2 = np.array([1, 2, 3, 4])

In [14]:
arr2

array([1, 2, 3, 4])

In [16]:
## 2차원 배열 생성
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
## 배열 크기 확인하기 ~.shape
arr1.shape
arr2.shape

(2, 3)

In [24]:
### array 에서 data type )array 에서는 list와 다르게 1개의 단일 데이터 타입만 허용됨.
mylist = [1, 3.14, "스마트", "1234"]
mylist

[1, 3, 14, '스마트', '1234']

In [25]:
list1 = [1, 2, 3, 3.14]
arr = np.array([1, 2, 3, 3.14])  # array가 정수를 실수로 바꿈


In [26]:
list1

[1, 2, 3, 3.14]

In [28]:
arr

array([1.  , 2.  , 3.  , 3.14])

In [30]:
arr1 = np.array([1, 2, 3, 3.14], dtype = int) #dtype :자료형이 가지는 원소의 데이터타입
arr1

array([1, 2, 3, 3])

In [32]:
arr2 = np.array([1, 3.14, "스마트", "1234"])
arr2

array(['1', '3.14', '스마트', '1234'], dtype='<U32')

In [34]:
#int 와 str타입이 혼재되어 있고 int로 dtype을 지정한 경우

arr3 = np.array([1, 3.14,  "1234"], dtype = int)
arr3

array([   1,    3, 1234])

In [36]:
##배열 전체 요소 개수 확인
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [37]:
print(arr1.size)

5


In [51]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
print(arr2.size)

6


In [43]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
print(arr3.size)
arr3.shape

12


(2, 2, 3)

In [50]:
# 배열 원소의 데이터 타입 확인
print(arr1.dtype)

int32


In [53]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],dtype="int64")
print(arr3.dtype)

int64


In [57]:
#배열의 차원 확인
print(arr1.ndim)
print(arr3.ndim)

1
3


In [71]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 = arr1.reshape(2, 2, 2)             #배열 모양 재 성형 
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [64]:
#연습문제
arr_ = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_
print("배열의 크기 : ",arr_.shape)
print("배열의 차원 : ", arr_.ndim)
print("배열의 개수 : ",arr_.size)

배열의 크기 :  (2, 2, 2)
배열의 차원 :  3
배열의 개수 :  8


In [69]:
list1 = [1, 2, 3, 4, 5, "345"]
list1
arr0 = np.array(list1)
arr0
list1 = np.array([1, 2, 3, 4, 5, "345"], dtype=int)   # astype("float")
list1

array([  1,   2,   3,   4,   5, 345])

In [70]:
list2 = [1, 2, 2.5, "인재", "파이썬", "345"]
arr0_ = np.array(list2)
arr0_

array(['1', '2', '2.5', '인재', '파이썬', '345'], dtype='<U32')

In [73]:
arr = np.array([1, 2, 3, 2.5, "인재", "파이썬", "345"])
arr

array(['1', '2', '3', '2.5', '인재', '파이썬', '345'], dtype='<U32')

In [74]:
# 0으로 초기화 
arr_zeros = np.zeros((3, 4))  # 기본적으로 실수로 생성됨 ), dtype=int 정수형으로 변환
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
# 1 로 초기화
arr_ones = np.ones((3, 4),dtype=int)  # 정수 변환
arr_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [130]:
# 특정한 값으로 배열 생성 : full
arr_full = np.full((5, 4), 7)
arr_full


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [80]:
# 1~50까지 값을 갖는 1차원 리스트 생성
list1 = []
for i in range(1, 51) :  #range(초기값, 끝값+1 , 간격)
    list1.append(i)
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [81]:
arr = np.array(list1)  #리스트를 이용하여 배열 생성


In [83]:
# 배열 생성하는 함수 : arange
arr = np.arange(1, 51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [84]:
arr1 = np.arange(2, 51, 2)
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [90]:
arr1_zeros = np.zeros((4, 4),dtype=int)
arr1_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [91]:
arr_ones = np.ones((10, 10), dtype=int)
arr_ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [92]:
arr = np.arange(3, 101, 3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [105]:
print(arr.size)
arr1 = arr.reshape((11, 3))
print(arr1)
print(arr1.shape)

33
[[ 3  6  9]
 [12 15 18]
 [21 24 27]
 [30 33 36]
 [39 42 45]
 [48 51 54]
 [57 60 63]
 [66 69 72]
 [75 78 81]
 [84 87 90]
 [93 96 99]]
(11, 3)


In [116]:
#랜덤값 생성
import random

In [117]:
arr = np.random.rand(2, 4)
arr

array([[0.56750989, 0.87253411, 0.88990089, 0.87490506],
       [0.73075552, 0.60440238, 0.38685672, 0.48866538]])

In [118]:
arr = np.random.randint(1, 45, size=(2, 6))#randint(시작,끝,size)
arr

array([[30, 24, 29, 26, 26, 20],
       [28,  2, 31, 15, 32, 26]])

In [119]:
# 타입 변경하기 :astype

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 = arr1.astype("float64")
arr2

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [120]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [121]:
# 연습
#1.0~1 사이의 값을 랜덤하게 가지는 6*4 배열 생성
#2. 1~100 사이의 값을 랜덤하게 가지는 5*5 배열을 생성하시오
#3. astype을 사용하여 2번의 배열을 실수형태로 변경

In [128]:
arr = np.random.rand(6, 4)
arr

array([[0.6408902 , 0.51768241, 0.20236397, 0.29192612],
       [0.42950066, 0.72306244, 0.92945903, 0.04992206],
       [0.82450866, 0.97327669, 0.05757195, 0.03508358],
       [0.49366355, 0.87718407, 0.13691288, 0.79905062],
       [0.96134658, 0.16705195, 0.75088629, 0.99098816],
       [0.29671737, 0.24217354, 0.04422701, 0.48160412]])

In [126]:
arr1 = np.random.randint(1, 101, size = (5, 5))
arr1

array([[ 51,  94,  53,  88,  71],
       [ 16,  26,  82,  34,  59],
       [ 64,   8,  87,  99,  63],
       [100,   3,  29,   4,  77],
       [ 60,  99,  18,  57,  12]])

In [127]:
arr2 = arr1.astype("float")
arr2

array([[ 51.,  94.,  53.,  88.,  71.],
       [ 16.,  26.,  82.,  34.,  59.],
       [ 64.,   8.,  87.,  99.,  63.],
       [100.,   3.,  29.,   4.,  77.],
       [ 60.,  99.,  18.,  57.,  12.]])