In [1]:
import numpy as np

In [ ]:
#인덱싱 
# - 파이썬 리스트와 동일한 개념으로 사용
#- ,를 사용하여 각 차원의 인덱스에 접근 가능


In [3]:
#1차원 벡터 인덱싱
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
x[3]
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


In [7]:
x = np.arange(10).reshape(2, 5)#arange로 원소 생성과 동시에 reshape으로 배열
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
x[0, : ]

array([0, 1, 2, 3, 4])

In [9]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [10]:
x[:, :1]

array([[0],
       [5]])

In [12]:
x[:, 3:5]

array([[3, 4],
       [8, 9]])

In [13]:
x[1, 1:4]

array([6, 7, 8])

In [ ]:
##슬라이싱 할 때, 인덱스 범위
# - [시작, 끝]

In [20]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
print(y[:, 3])  #인덱싱  :차원축소
print(y[:,3:4]) #슬라이싱  :차원유지

[ 3  8 13]
[[ 3]
 [ 8]
 [13]]


In [36]:
y[:1, :]

array([[0, 1, 2, 3, 4]])

In [29]:
y[1,:]
y[1:2, :]

array([[5, 6, 7, 8, 9]])

In [38]:
y[:2, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [42]:
# 3차원 슬라이싱 
z = np.arange(54).reshape(2, 3, 9)
print(z)

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]
  [18 19 20 21 22 23 24 25 26]]

 [[27 28 29 30 31 32 33 34 35]
  [36 37 38 39 40 41 42 43 44]
  [45 46 47 48 49 50 51 52 53]]]


In [ ]:
# 1. 첫번째 2차원 행렬을 슬라이싱
# 2. 그 다음 2차원 행렬의 행 두개를 슬라이싱
# 3. 슬라이싱 한 행렬의 행의 열 원소 다 가져오기

In [44]:
z[:1, :2, :]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]])

In [47]:
z[1:2, :3, :]

array([[[27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53]]])

In [49]:
z[:1, :2, 6:]

array([[[ 6,  7,  8],
        [15, 16, 17]]])

In [51]:
z[1:2, :2, 6:]

array([[[33, 34, 35],
        [42, 43, 44]]])

In [53]:
z[1:2, :3, 3:6] #슬라이싱

array([[[30, 31, 32],
        [39, 40, 41],
        [48, 49, 50]]])

In [54]:
z[1, :, 3:6] # 인덱싱 :차원축소

array([[30, 31, 32],
       [39, 40, 41],
       [48, 49, 50]])